language: node_js
node_js: "12"
cache: npm
script:
    - "npm run dev"
deploy:
    provider: heroku
    api_key:
        secure: 3ed52c1a-1220-426c-8cb2-f08fd7c1e6f3
    app: Layout-sigma
    on:
        repo: Johndev85/Layout-sigma
